package io.github.mudrichenkoevgeny.kmp.feature.user.ui.screen.profile.totp

import io.github.mudrichenkoevgeny.kmp.core.common.error.model.AppError
import io.github.mudrichenkoevgeny.kmp.feature.user.usecase.user.security.EnableTotpUseCase
import io.github.mudrichenkoevgeny.kmp.feature.user.usecase.user.security.SetupTotpUseCase
import io.github.mudrichenkoevgeny.kmp.feature.user.utils.FieldValidator
import io.github.mudrichenkoevgeny.shared.foundation.core.security.domain.model.totprecoverycodes.TotpRecoveryCodes
import io.github.mudrichenkoevgeny.shared.foundation.core.security.domain.model.totpsetup.TotpSetup

/**
 * UI state for the TOTP settings management.
 */
sealed interface TotpSettingsScreenState {

    /** Initial loading of current security state. */
    data object Loading : TotpSettingsScreenState

    /**
     * TOTP is currently disabled. Shows an option to start the setup.
     *
     * @param actionLoading true when [SetupTotpUseCase] is in progress.
     * @param actionError error from the last setup attempt.
     */
    data class Disabled(
        val actionLoading: Boolean = false,
        val actionError: AppError? = null
    ) : TotpSettingsScreenState

    /**
     * TOTP setup is in progress. Shows QR code and manual entry key.
     *
     * @param setup details generated by [SetupTotpUseCase].
     * @param code current verification code text for confirmation.
     * @param actionLoading true when [EnableTotpUseCase] is in progress.
     * @param actionError error from the last enable attempt.
     */
    data class SetupInProgress(
        val setup: TotpSetup,
        val code: String = "",
        val actionLoading: Boolean = false,
        val actionError: AppError? = null
    ) : TotpSettingsScreenState {
        val canConfirm: Boolean = code.length == FieldValidator.TOTP_CODE_LENGTH && code.all { it.isDigit() } && !actionLoading
    }

    /**
     * TOTP is active. Shows recovery codes and an option to disable.
     *
     * @param recoveryCodes active backup codes.
     * @param actionLoading true when disabling or regenerating codes.
     * @param actionError error from the last action.
     */
    data class Enabled(
        val recoveryCodes: TotpRecoveryCodes,
        val showDisableConfirmation: Boolean = false,
        val showRegenerateConfirmation: Boolean = false,
        val actionLoading: Boolean = false,
        val actionError: AppError? = null
    ) : TotpSettingsScreenState

    /** Critical error during state initialization. */
    data class Error(val error: AppError) : TotpSettingsScreenState
}
